name: frontend 
description: A new Flutter project.

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.18.0
  dio: ^5.0.0
  syncfusion_flutter_gauges: ^29.1.38
  

  english_words: ^4.0.0
  provider: ^6.0.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0
  dart_jsonwebtoken: ^2.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true